### ISSUE TITLE
Wrong damage calculation

### ISSUE THREAD

**Issue by nyanchii** [ga0321/SoulMeter#2]
Example
[Chat] [System] You dealt 939026(+435473)

939026 means base damage + soulstone damage
435473 means soulstone damage

But current meter calculate [base damage + soulstone damage + soulstone damage]
And It makes dps inflates

**Comment by AFNGP** [comment]
You mentioned that you "fixed soulstone damage in 1.2.9.4" release. However, you are calculating the damage wrong.

The old method of calculating damage already takes soulstone damage into account. Hence, what you did is only add soulstone damage again.

Training master has 1,000,000,000 HP. 
![image](https://user-images.githubusercontent.com/104720415/166145129-27c375e9-2586-4820-a60d-9f7a68cc0d1e.png)

But when killing it, meter shows 1,500,000,000 damage, which is inaccurate.
![image](https://user-images.githubusercontent.com/104720415/166145174-37727b5f-60e5-4cfb-8682-e1a5a43996c8.png)

Please note that in this case, the yellow number already has the soulstone damage calculated in it
![image](https://user-images.githubusercontent.com/104720415/166145461-3a136aa5-4676-4d18-9a3e-1765c9b533ec.png)
![image](https://user-images.githubusercontent.com/104720415/166145469-77b17443-7dbd-40f1-a93e-0713c22d6013.png)
![image](https://user-images.githubusercontent.com/104720415/166145481-6826f599-0f32-4a62-9341-d6649b0475d6.png)

**Comment by ga0321** [comment]
Thanks for reporting this. Fixed with v1.2.9.6.
