### ISSUE TITLE
Old version and closed source

### ISSUE THREAD

**Issue by AFNGP** [ga0321/SoulMeter#4]
Hello, thank you for your efforts with providing the meter,

I would like to ask, is there a reason as to why you are using a very old source code version of the meter? The meter is lacking features that have been implemented since October 2021 such as boss aggro. 

In addition, is there any reason as to why you are not publicly providing the source code? The meter has been open source since its creation and it is not fair for it to be private now after all people's contributions to it. We can understand if you want the decryption part private and we are not asking for it, but there is no reason to keep meter code private. 

Thank you for your understanding in advance

**Comment by ga0321** [comment]
Hello, thanks for your suggestion.

I uploaded source code except decryption part.
Boss aggro bug is fixed with v1.2.9.8.
