### ISSUE TITLE
Maze Pause and Maze Stop Issues

### ISSUE THREAD

**Issue by AFNGP** [ga0321/SoulMeter#7]
BS Hard Phase 1: meter doesn't pause between phase 1 and phase 2
BS Hard Phase 2: meter doesn't stop as soon as Tenebris is dead

Fix (in `Packet/SWPacketDamage.h`):
- Add `31310103` to `pauseIdList` 
- Add `31310107` to `endIdList`

More info and full credits to NyanChii: https://github.com/fearek/DPSMeter/commit/8af33ffcbe1b997a9c1ac616db8058195ffc719d

**Comment by ga0321** [comment]
thank you, fix in [7bd925b](https://github.com/ga0321/SoulMeter/commit/7bd925b2ca73753442c4081aadadd0e8d15c7090)
